### ISSUE TITLE
Sox updated, RHVoice compilation failed

### ISSUE THREAD

**Issue by derfenix** [RHVoice/RHVoice#2]
After updating sox to 14.4 RHVoice fails to work and compile. Compilation fails with error:

src/lib/lib.c: In function 'hts_synth':
src/lib/lib.c:907:51: error: 'SOX_OPTION_DEFAULT' undeclared (first use in this function)
src/lib/lib.c:907:51: note: each undeclared identifier is reported only once for each function it appears in
scons: **\* [build/linux2/lib/lib.os] Error 1
scons: building terminated because of errors.
